### ISSUE TITLE
Not connecting to remote nodes

### ISSUE THREAD

**Issue by adamrigg** [iotaledger/cli-app#19]
I can't seem to actually connect to any of the nodes listed on iotasupport using the node command. I can connect to those nodes using the gui wallet. The cli returns to the prompt, with the selected addresses replacing the localhost prompt, but with no change to the red "disconnected" status.

![image](https://user-images.githubusercontent.com/13562819/33493317-6ec684b0-d69e-11e7-92ad-ff916646dfc7.png)

**Comment by adamrigg** [comment]
![image](https://user-images.githubusercontent.com/13562819/33493291-55f7f8d8-d69e-11e7-83f0-e71789b13c89.png)

**Comment by MCM-Mike** [comment]
Having the same issues as adamrigg on the following system:

> Debian GNU/Linux 8 \n \l
> Linux sr1 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64 GNU/Linux
> node --version
> v8.9.1

**Comment by plenarius** [comment]
I too had this error and discovered it was an API Version difference. Here's what I did to fix.
```
git clone https://github.com/iotaledger/cli-app && cd cli-app
```
edit the package.json and change
`"iota.lib.js": "^0.3.0",`
to
`"iota.lib.js": "^0.4.3",`

Then ran:
`sudo npm install -g
`

**Comment by mark-bradshaw** [comment]
v1.0.5 published
