### ISSUE TITLE
Store user info locally

### ISSUE THREAD

**Issue by mark-bradshaw** [iotaledger/cli-app#2]
`os.homedir`

node connection info
mwm
depth

Ask for permission to store.

**Comment by domschiener** [comment]
Why would you want to store nodes? Unless we want to couple the CLI more closely with IRI.

**Comment by mark-bradshaw** [comment]
I want to store the connection info for nodes I've visited, and find a way to make connecting back easier.  I have three nodes that I regularly connect to, but I keep having to lookup the ip address.  So this is for convenience purposes.

**Comment by mark-bradshaw** [comment]
or if switching to a testnet node, maybe keep track of the associated mwm.
