### ISSUE TITLE
Output of healthcheck not printing number of neighbors

### ISSUE THREAD

**Issue by alfredch** [iotaledger/cli-app#3]
iota (http://localhost:14265 \u2713)$ healthcheck
Free memory: \u2713
Node sync: out of sync
Number of neighbors (undefined-undefined): you need between 4 and 9 neighbors.  You have ## **${data.neighbors.length}**
Inactive neighbor: /213.174.253.29:14265

**Comment by mark-bradshaw** [comment]
Thanks @alfredch.  I changed my data structures, and inadvertently broke that command.  It's fixed now if you pull latest.
