### ISSUE TITLE
Timeout on every Request

### ISSUE THREAD

**Issue by Fumlop** [iotaledger/cli-app#32]
I try to safe some funds from an used adress... but everytime i try this happens.
Any Ideas?

the transfer is made.  This can take a few minutes.60
Error: Invalid Response: <html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>

**Comment by mark-bradshaw** [comment]
No ideas.  Sorry.
