### ISSUE TITLE
Request Error: COMMAND attachToTangle is not available on this node with iota-cli-app@1.0.8

### ISSUE THREAD

**Issue by rnagler** [iotaledger/cli-app#38]
Maybe related to issue #1067 for iotaledger/wallet:
After snapshot I tried to send 18 iotas with wallet 2.5.7 and got message
ERROR: PRIVATE KEY REUSE DETECTED (no pending transactions) 
So I tried send same with iota-cli-app@1.0.8: and got totally different Error:
Error: Request Error: COMMAND attachToTangle is not available on this node
tried this with different nodes, always same

See session log:
iota (http://eugeneoldisoft.iotasupport.com:14265 ✓) 18ι : nodeinfo
appName:                            IRI
appVersion:                         1.4.2.1
jreAvailableProcessors:             8
jreFreeMemory:                      10014600848
jreVersion:                         1.8.0_152
jreMaxMemory:                       12882804736
jreTotalMemory:                     12882804736
latestMilestone:                    CDVIOZTYVXZNCNZUJWYHVMRVQNYWIMLEZNFBTDHUEBOSZIMVUWKXRJKFYFYH9ZDOWEDRXSQOQRFUA9999
latestMilestoneIndex:               338717
latestSolidSubtangleMilestone:      CDVIOZTYVXZNCNZUJWYHVMRVQNYWIMLEZNFBTDHUEBOSZIMVUWKXRJKFYFYH9ZDOWEDRXSQOQRFUA9999
latestSolidSubtangleMilestoneIndex: 338717
neighbors:                          8
packetsQueueSize:                   0
time:                               1517255848741
tips:                               8955
transactionsToRequest:              9

iota (http://eugeneoldisoft.iotasupport.com:14265 ✓) 18ι : balance
One moment while we collect the data.
Your current balance is 18ι.
iota (http://eugeneoldisoft.iotasupport.com:14265 ✓) 18ι : transfer xxx 18 
One moment while the transfer is made.  This can take a few minutes.
Error: Request Error: COMMAND attachToTangle is not available on this node
iota (http://eugeneoldisoft.iotasupport.com:14265 ✓) 18ι 👍 

changing to another node https://iotanode.us:443 it did work with cli, but NOT with light wallet
So how could the enduser understand this behaviour?

**Comment by dsir-minute** [comment]
hi all,
@rnagler  , me too !
I get "Error: Request Error: COMMAND attachToTangle is not available on this node"
when I send a transfer while connected to 
node http://iotanode.party:14265 or to
node https://nodes.thetangle.org:443

But when I use node https://iotanode.us:443
my transfer gets accepted (I did not say confirmed)

Please  try to explain what happens with  https://iotanode.us:443
that is missing on the 2 others ?
tks

**Comment by dsir-minute** [comment]
a few days after my previous and failed attempts,  http://iotanode.party:14265 has begun to accept my connections and requests.
I cloned this repo and made a few convenient mods (inc. lib 0.4.7) , you can find them @ https://github.com/dsir-minute/raxycli-app

**Comment by mark-bradshaw** [comment]
@dsir-minute If you want to create a PR with your changes I'll take a look.
